# Generated by Django 3.2.15 on 2022-09-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_reservation_select_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='select_date',
            new_name='reservation_date',
        ),
    ]
