# Generated by Django 3.2.15 on 2022-09-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_rename_select_date_reservation_reservation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='idUser',
            new_name='user_name',
        ),
    ]
