# Generated by Django 3.2.15 on 2022-09-24 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_rename_iduser_reservation_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='idUser',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='idUser',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='user_name',
            new_name='username',
        ),
    ]
