# Generated by Django 3.2.15 on 2022-09-24 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_auto_20220924_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='itemsmenu',
            options={'verbose_name': 'ItemsMenu', 'verbose_name_plural': 'ItemsMenu'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
