# Generated by Django 3.2.15 on 2022-09-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20220924_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsmenu',
            old_name='idMenu',
            new_name='id_menu',
        ),
        migrations.RenameField(
            model_name='itemsmenu',
            old_name='idOrder',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='mealDescription',
            new_name='meal_description',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='mealName',
            new_name='meal_name',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='totalPrice',
            new_name='total_price',
        ),
    ]
