# Generated by Django 3.2.15 on 2022-09-24 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_auto_20220924_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsmenu',
            name='id_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_meal', to='restaurant.menu'),
        ),
        migrations.AlterField(
            model_name='itemsmenu',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_order', to='restaurant.orders'),
        ),
    ]
