# Generated by Django 3.2.15 on 2022-09-24 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_auto_20220924_1521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemsMenu',
            new_name='Basket',
        ),
    ]
