# Generated by Django 3.2.15 on 2022-09-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_rename_itemsmenu_basket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Basket', 'verbose_name_plural': 'Basket'},
        ),
    ]
