# Generated by Django 3.2.15 on 2022-10-03 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_customer_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='number_of_people',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
