# Generated by Django 3.2.15 on 2022-10-12 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_remove_orders_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
