# Generated by Django 3.2.15 on 2022-10-12 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_remove_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
    ]
